// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 8.8
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container0").wowSlider({effect:"blur",prev:"",next:"",duration:20*100,delay:20*100,width:1280,height:800,autoPlay:true,autoPlayVideo:false,playPause:false,stopOnHover:false,loop:false,bullets:0,caption:false,captionEffect:"parallax",controls:false,controlsThumb:false,responsive:2,fullScreen:false,gestures:2,onBeforeStep:0,images:[{src:"./imgmiddle1.png",title:"img-middle-1"},{src:"./imgmiddle2.png",title:"img-middle-2"},{src:"./imgmiddle3.png",title:"img-middle-3"},{src:"./imgmiddle4.png",title:"img-middle-4",href:"http://wowslider.net"},{src:"./imgmiddle5.png",title:"img-middle-5"}]});